# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 09:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_auto_20160424_0818'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='awaiting_approval',
            field=models.BooleanField(default=True),
        ),
    ]
