# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-04-24 11:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0003_project_awaiting_approval'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, b'Scientist'), (2, b'Student'), (3, b'Scientist')], default=1),
        ),
        migrations.AlterUniqueTogether(
            name='projectrole',
            unique_together=set([('user', 'project')]),
        ),
    ]
