# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 08:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_comment'),
        ('projects', '0006_auto_20160506_1631'),
    ]

    operations = [
    ]
