# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-11 09:19
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_auto_20160511_0849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='projectactivity',
            options={'verbose_name_plural': 'project activities'},
        ),
    ]
