# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 07:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_auto_20160511_1000'),
    ]

    operations = [
        migrations.AlterField(
            model_name='projectrole',
            name='role',
            field=models.PositiveIntegerField(choices=[(1, b'Scientist'), (2, b'Student'), (3, b'Citizens Science')], default=1),
        ),
    ]
