# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 07:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160513_0714'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='downvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='unique_visits',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='upvotes',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='project',
            name='visits',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
