# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-13 07:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_auto_20160513_0714'),
        ('projects', '0012_auto_20160512_0723'),
    ]

    operations = [
    ]
