# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 09:15
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0014_merge'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='picture',
            field=core.fields.RestrictedNonAnimatedImageField(blank=True, null=True, upload_to=b'projects/picture'),
        ),
    ]
