# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 09:57
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0016_auto_20160516_0951'),
    ]

    operations = [
        migrations.RenameField(
            model_name='projectrating',
            old_name='rate_date',
            new_name='modified',
        ),
        migrations.AddField(
            model_name='projectrating',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=datetime.datetime(2016, 5, 16, 9, 57, 14, 342674, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
