# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-17 22:08
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0017_auto_20160516_0957'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='favorites',
            field=models.ManyToManyField(related_name='favorites_projects', through='projects.ProjectFavorite', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='project',
            name='ratings',
            field=models.ManyToManyField(related_name='rates_projects', through='projects.ProjectRating', to=settings.AUTH_USER_MODEL),
        ),
    ]
