# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-26 07:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0018_auto_20160517_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectactivity',
            name='project',
        ),
        migrations.RemoveField(
            model_name='projectactivity',
            name='responses',
        ),
        migrations.RemoveField(
            model_name='projectactivity',
            name='user',
        ),
        migrations.AlterUniqueTogether(
            name='projectactivityresponse',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='projectactivityresponse',
            name='activity',
        ),
        migrations.RemoveField(
            model_name='projectactivityresponse',
            name='user',
        ),
        migrations.DeleteModel(
            name='ProjectActivity',
        ),
        migrations.DeleteModel(
            name='ProjectActivityResponse',
        ),
    ]
