# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-06 22:28
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0019_auto_20160526_0732'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', core.fields.RestrictedFile(blank=True, null=True, upload_to=b'projects/attachment')),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attachments', to='projects.Project')),
            ],
        ),
    ]
