# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-06 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='avatar',
            field=models.ImageField(blank=True, null=True, upload_to=b'/uploads/avatar/'),
        ),
        migrations.AddField(
            model_name='user',
            name='views',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
