# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-16 09:15
from __future__ import unicode_literals

import core.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_userlog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='avatar',
            field=core.fields.RestrictedNonAnimatedImageField(blank=True, null=True, upload_to=b'users/avatar'),
        ),
    ]
