# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-05-25 08:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20160516_0915'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='about_me',
            field=models.CharField(blank=True, max_length=50000, null=True),
        ),
    ]
