# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-03 21:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0002_auto_20160527_0932'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='projectactivity',
            name='allowed_submissions',
        ),
    ]
