# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-06-07 10:22
from __future__ import unicode_literals

import core.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('activities', '0003_remove_projectactivity_allowed_submissions'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectActivityAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', core.fields.RestrictedFile(blank=True, null=True, upload_to=b'projects/attachment')),
                ('activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_attachments', to='activities.ProjectActivity')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ProjectActivityResponseAttachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('object', core.fields.RestrictedFile(blank=True, null=True, upload_to=b'projects/attachment')),
                ('response', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='activity_response_attachments', to='activities.ProjectActivityResponse')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
